### ISSUE TITLE
ODF_6: Embedded Objects

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/odf-validator#94]
If there are any embedded files then they **MUST** be one of the acceptable formats.

The  list of permitted file formats is:

* TIFF (.tiff) for regular office documents in the form of text, spreadsheets and images
* JPEG2000 (.jp2) for large drawings, maps and photos
* MP3 (.mp3) for audio files
* WAV (.wav) for audio files where high quality is important
* MPEG2 (.mpg) for video files
* MPEG4 (.mpg) for video files
* ODF 1.3 spreadsheet format (.ods)

This means that embedded files must be either one of the above types by nature of itself, be converted to one of the above types or be removed. Bek 128 gives rules for how this information should be conveyed in an AVID collection.

These rules are valid even if there are multiple layers of embedding.

An ODS validator must be able to report the following information:

* Source File
* Embedded File name
* File type
* Cell row
* Cell column

**Comment by dewhattens** [comment]
When extracting embedded objects from the zip file, they can take one of two forms -- a file-based Object or a directory-based Object.

The directory-based objects occur most frequently when an OpenOffice/LibreOffice document is embedded within another OpenOffice/LibreOffice document. If you look at the directory-based object's sub-directory, it will contain the same types of files you would find in a standard document such as content.xml, settings.xml, styles.xml, etc. Unfortunately you can't zip up the directory-based object and give it an odp, odt, or ods extension because the directory-based object is missing it's own manifest.xml file. It's possible to take the manifest.xml file in the parent document, modify it, then combine it with the files in the directory-based object but it can get difficult depending on the complexity of the parent file and embedded object.

The file-based objects occur most frequently when the embedded object was inserted by Microsoft Office and/or is a file type that cannot be expressed using the OpenDocument Format. In these cases the native file is wrapped in a Microsoft OLE stream

**Comment by carlwilson** [comment]
Closed by #135
